# --- !Ups

create table "clients" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "age" int not null
);

create table "suppliers" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "desc" int not null
);

# --- !Downs

drop table "people" if exists;
drop table "suppliers" if exists;
