# --- !Ups

CREATE TABLE "clients" (
  "id"   BIGINT GENERATED BY DEFAULT AS IDENTITY ( START WITH 1) NOT NULL PRIMARY KEY,
  "name" VARCHAR                                                 NOT NULL,
  "age"  INT                                                     NOT NULL
);

CREATE TABLE "sellers" (
  "id"   BIGINT GENERATED BY DEFAULT AS IDENTITY ( START WITH 1) NOT NULL PRIMARY KEY,
  "name" VARCHAR                                                 NOT NULL,
  "desc" VARCHAR                                                 NOT NULL
);

CREATE TABLE "suppliers" (
  "id"   BIGINT GENERATED BY DEFAULT AS IDENTITY ( START WITH 1) NOT NULL PRIMARY KEY,
  "name" VARCHAR                                                 NOT NULL,
  "desc" VARCHAR                                                 NOT NULL
);

CREATE TABLE "products" (
  "id"         BIGINT GENERATED BY DEFAULT AS IDENTITY ( START WITH 1) NOT NULL PRIMARY KEY,
  "name"       VARCHAR                                                 NOT NULL,
  "supplierId" BIGINT                                                  NOT NULL,
  "desc"       VARCHAR                                                 NOT NULL,
  FOREIGN KEY ("supplierId") REFERENCES "suppliers" ("id")
);

CREATE TABLE "catalogues" (
  "id"       BIGINT GENERATED BY DEFAULT AS IDENTITY ( START WITH 1) NOT NULL PRIMARY KEY,
  "sellerId" BIGINT,
  FOREIGN KEY ("sellerId") REFERENCES "sellers" ("id")
  ON DELETE CASCADE
);

CREATE TABLE "catalogue_items" (
  "id"          BIGINT GENERATED BY DEFAULT AS IDENTITY ( START WITH 1) NOT NULL PRIMARY KEY,
  "catalogueId" BIGINT                                                  NOT NULL,
  "productId"   BIGINT                                                  NOT NULL,
  "price"       BIGINT                                                  NOT NULL,
  "desc"        VARCHAR,
  FOREIGN KEY ("productId") REFERENCES "products" ("id"),
  FOREIGN KEY ("id") REFERENCES "catalogues" ("id"),
  CONSTRAINT UniqueProductToCatalog UNIQUE ("catalogueId", "productId")
)


  # --- !Downs

DROP TABLE "people" IF EXISTS;
DROP TABLE "sellers" IF EXISTS;
DROP TABLE "suppliers" IF EXISTS;
DROP TABLE "products" IF EXISTS;
DROP TABLE "catalogue_items" IF EXISTS;
