# --- !Ups

create table "clients" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "age" int not null
);

create table "sellers" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "desc" varchar not null
);

create table "suppliers" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "desc" varchar not null
);

create table "products" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "supplierId" bigint not null,
  "desc" varchar not null,
  FOREIGN KEY ("supplierId") REFERENCES "suppliers"("id")
);

create table "wallets" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "clientId" bigint not null,
  "sum_in_wallet" bigint not null,
  FOREIGN KEY ("clientId") REFERENCES "clients"("id")
)


# --- !Downs

drop table "people" if exists;
drop table "sellers" if exists;
drop table "suppliers" if exists;
drop table "products" if exists;
